fix/pipeline: update the step for test deployment

diff --git a/.github/workflows/merge-main.yml b/.github/workflows/merge-main.yml
--- a/.github/workflows/merge-main.yml
+++ b/.github/workflows/merge-main.yml
@@ -36,7 +36,7 @@ jobs:
 
   # # https://github.com/snyk/snyk
   # snyk:
-  #   name: Dependency Scan
+  #   name: Dependency Report
   #   runs-on: ubuntu-latest
   #   steps:
   #   - name: Checkout repository
@@ -55,9 +55,55 @@ jobs:
   #     with:
   #       sarif_file: snyk.sarif
 
+  # # https://github.com/marketplace/actions/aqua-security-trivy
+  # trivy-backend:
+  #   name: Backend Image Report
+  #   runs-on: ubuntu-18.04
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
+
+  #     # Backend container scan
+  #     - name: Trivy Image Scan
+  #       uses: aquasecurity/trivy-action@0.3.0
+  #       with:
+  #         image-ref: ${{ env.REGISTRY }}/${{ github.repository }}:test-backend
+  #         ignore-unfixed: true
+  #         severity: CRITICAL
+  #         format: "sarif"
+  #         output: "trivy-results-backend.sarif"
+
+  #     - name: Upload Trivy results to GitHub Security tab
+  #       uses: github/codeql-action/upload-sarif@v2
+  #       with:
+  #         sarif_file: "trivy-results-backend.sarif"
+
+  # # https://github.com/marketplace/actions/aqua-security-trivy
+  # trivy-frontend:
+  #   name: Frontend Image Report
+  #   runs-on: ubuntu-18.04
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
+
+  #     # Frontend container scan
+  #     - name: Trivy Image Scan
+  #       uses: aquasecurity/trivy-action@0.3.0
+  #       with:
+  #         image-ref: ${{ env.REGISTRY }}/${{ github.repository }}:test-frontend
+  #         ignore-unfixed: true
+  #         severity: CRITICAL
+  #         format: "sarif"
+  #         output: "trivy-results-frontend.sarif"
+
+  #     - name: Upload Trivy results to GitHub Security tab
+  #       uses: github/codeql-action/upload-sarif@v2
+  #       with:
+  #         sarif_file: "trivy-results-frontend.sarif"
+
   # https://github.com/marketplace/actions/aqua-security-trivy
   trivy-repo:
-    name: Repository Scan
+    name: Repository Report
     runs-on: ubuntu-18.04
     steps:
       - name: Checkout code
@@ -79,7 +125,7 @@ jobs:
 
   # https://github.com/marketplace/actions/aqua-security-trivy
   trivy-rhel-ubi:
-    name: Base Image Scan
+    name: Base Image Report
     runs-on: ubuntu-latest
     timeout-minutes: 5
     steps:
@@ -113,126 +159,155 @@ jobs:
           owner: orgs/bcgov
           skip_tags: prod-frontend,prod-backend
 
-  deploy-test:
-    name: TEST Deployment
-    needs:
-      - cleanup-ghcr
-      - codeql
-      # - snyk
-      - trivy-repo
-      - trivy-rhel-ubi
-    runs-on: ubuntu-latest
-    environment:
-      name: test
-    env:
-      ZONE: test
-    steps:
-      - uses: actions/checkout@v2
-      - name: Deploy
-        run: |
-          # Login to OpenShift and select project
-          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
-          oc project ${{ secrets.OC_NAMESPACE }}
+  # deploy-test:
+  #   name: TEST Deployment
+  #   runs-on: ubuntu-latest
+  #   environment:
+  #     name: test
+  #   env:
+  #     ZONE: test
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Deploy
+  #       run: |
+  #         # Login to OpenShift and select project
+  #         oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
+  #         oc project ${{ secrets.OC_NAMESPACE }}
 
-          # Clear stale images for import/replacement
-          if [ $(oc get is -l app=${{ env.NAME }}-${{ env.ZONE }} -o name | grep -v database | wc -l) -gt 0 ]; then
-            oc delete is -l app=${{ env.NAME }}-${{ env.ZONE }}
-          fi
+  #         # Clear stale images for import/replacement
+  #         if [ $(oc get is -l app=${{ env.NAME }}-${{ env.ZONE }} -o name | grep -v database | wc -l) -gt 0 ]; then
+  #           oc delete is -l app=${{ env.NAME }}-${{ env.ZONE }}
+  #         fi
 
-          # Create frontend config (Remove the old one if exists)
-          oc delete configmap ${{ env.NAME }}-${{ env.ZONE }}-frontend 2> /dev/null \
-            || true && echo "No existing frontend config"
-          oc create configmap ${{ env.NAME }}-${{ env.ZONE }}-frontend  \
-            --from-literal=config.js="const config = (() => { return { VITE_BACKEND_URL: 'https://${{ env.NAME }}-${{ env.ZONE }}-backend.apps.silver.devops.gov.bc.ca'}; })();"
+  #         # Create frontend config (Remove the old one if exists)
+  #         oc delete configmap ${{ env.NAME }}-${{ env.ZONE }}-frontend 2> /dev/null \
+  #           || true && echo "No existing frontend config"
+  #         oc create configmap ${{ env.NAME }}-${{ env.ZONE }}-frontend  \
+  #           --from-literal=config.js="const config = (() => { return { VITE_BACKEND_URL: 'https://${{ env.NAME }}-${{ env.ZONE }}-backend.apps.silver.devops.gov.bc.ca'}; })();"
 
-          # Process and apply deployment templates
-          oc process -f .github/openshift/deploy.database.yml -p ZONE=${{ env.ZONE }} | oc apply -f -
-          oc process -f .github/openshift/deploy.backend.yml -p ZONE=${{ env.ZONE }} \
-            -p PROMOTE=${{ github.repository }}:${{ env.ZONE }}-backend \
-            -p EMAIL_USERNAME=${{ secrets.CHES_SERVICE_CLIENT }} \
-            -p EMAIL_PASSWORD=${{ secrets.CHES_CLIENT_PASSWORD }} \
-            -p EMAIL_TOKEN_URL='https://oidc.gov.bc.ca/auth/realms/jbd6rnxw/protocol/openid-connect/token' \
-            -p EMAIL_API_URL='https://ches-dev.apps.silver.devops.gov.bc.ca/api/v1' \
-            -p NODE_ENV='development' | oc apply -f -
-          oc process -f .github/openshift/deploy.frontend.yml -p ZONE=${{ env.ZONE }} \
-            -p PROMOTE=${{ github.repository }}:${{ env.ZONE }}-frontend | oc apply -f -
+  #         # Process and apply deployment templates
+  #         oc process -f .github/openshift/deploy.database.yml -p ZONE=${{ env.ZONE }} | oc apply -f -
+  #         oc process -f .github/openshift/deploy.backend.yml -p ZONE=${{ env.ZONE }} \
+  #           -p PROMOTE=${{ github.repository }}:${{ env.ZONE }}-backend \
+  #           -p EMAIL_USERNAME=${{ secrets.CHES_SERVICE_CLIENT }} \
+  #           -p EMAIL_PASSWORD=${{ secrets.CHES_CLIENT_PASSWORD }} \
+  #           -p EMAIL_TOKEN_URL='https://oidc.gov.bc.ca/auth/realms/jbd6rnxw/protocol/openid-connect/token' \
+  #           -p EMAIL_API_URL='https://ches-dev.apps.silver.devops.gov.bc.ca/api/v1' \
+  #           -p NODE_ENV='development' | oc apply -f -
+  #         oc process -f .github/openshift/deploy.frontend.yml -p ZONE=${{ env.ZONE }} \
+  #           -p PROMOTE=${{ github.repository }}:${{ env.ZONE }}-frontend | oc apply -f -
 
-          # Follow any active rollouts (see deploymentconfigs)
-          oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-database -w
+  #         # Follow any active rollouts (see deploymentconfigs)
+  #         oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-database -w
 
-          # Run database migration  
-          oc exec dc/${{ env.NAME }}-${{ env.ZONE }}-database -- psql -d ${{ env.NAME }} -U ${{ env.NAME }} -c "$(cat backend/src/databasescripts/fsa.sql)"
+  #         # Run database migration
+  #         oc exec dc/${{ env.NAME }}-${{ env.ZONE }}-database -- psql -d ${{ env.NAME }} -U ${{ env.NAME }} -c "$(cat backend/src/databasescripts/fsa.sql)"
 
-          oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-backend -w
-          oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-frontend -w
+  #         oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-backend -w
+  #         oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-frontend -w
 
-          # Remove completed build runs, build pods and deployment pods
-          for p in $(oc get po | grep "Completed" | awk '{print $1}')
-          do
-            oc delete po ${p}
-          done
+  #         # Remove completed build runs, build pods and deployment pods
+  #         for p in $(oc get po | grep "Completed" | awk '{print $1}')
+  #         do
+  #           oc delete po ${p}
+  #         done
 
-  deploy-prod:
-    name: PROD Deployment
-    needs:
-      - deploy-test
-    runs-on: ubuntu-latest
-    environment:
-      name: prod
-    env:
-      ZONE: prod
-      PREV: test
-    steps:
-      - uses: actions/checkout@v2
-      - name: Deploy
-        run: |
-          # Login to OpenShift and select project
-          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
-          oc project ${{ secrets.OC_NAMESPACE }}
+  # zap-backend:
+  #   name: Backend Pen Tests
+  #   needs:
+  #     - deploy-test
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
 
-          # Clear stale images for import/replacement
-          if [ $(oc get is -l app=${{ env.NAME }}-${{ env.ZONE }} -o name | grep -v database | wc -l) -gt 0 ]; then
-            oc delete is -l app=${{ env.NAME }}-${{ env.ZONE }}
-          fi
+  #     - name: ZAP Scan
+  #       uses: zaproxy/action-full-scan@v0.3.0
+  #       with:
+  #         target: https://${{ env.NAME }}-test-backend.apps.silver.devops.gov.bc.ca/
+  #         cmd_options: "-a"
+  #         allow_issue_writing: true
+  #         fail_action: false
 
-          # Cancel db backup rollout if exists
-          if [ $(oc get dc -l app=backup-container -o name | wc -l) -gt 0 ]; then
-            oc rollout cancel dc/${{ env.NAME }}-${{ env.ZONE }}-dbbackup 2> /dev/null \
-              || true && echo "No rollout in progress"
-          fi
+  # zap-frontend:
+  #   name: Frontend Pen Tests
+  #   needs:
+  #     - deploy-test
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
 
-          # Create frontend config (Remove the old one if exists)
-          oc delete configmap ${{ env.NAME }}-${{ env.ZONE }}-frontend 2> /dev/null \
-            || true && echo "No existing frontend config"
-          oc create configmap ${{ env.NAME }}-${{ env.ZONE }}-frontend  \
-            --from-literal=config.js="const config = (() => { return { VITE_BACKEND_URL: 'https://${{ env.NAME }}-${{ env.ZONE }}-backend.apps.silver.devops.gov.bc.ca'}; })();"
+  #     - name: ZAP Scan
+  #       uses: zaproxy/action-full-scan@v0.4.0
+  #       with:
+  #         target: https://${{ env.NAME }}-test-frontend.apps.silver.devops.gov.bc.ca/
+  #         cmd_options: "-a"
+  #         allow_issue_writing: true
+  #         fail_action: false
 
-          # Process and apply deployment templates
-          oc process -f .github/openshift/deploy.database.yml -p ZONE=${{ env.ZONE }} | oc apply -f -
-          oc process -f .github/openshift/deploy.backend.yml -p ZONE=${{ env.ZONE }} \
-            -p PROMOTE=${{ github.repository }}:${{ env.PREV }}-backend \
-            -p EMAIL_USERNAME=${{ secrets.CHES_SERVICE_CLIENT }} \
-            -p EMAIL_PASSWORD=${{ secrets.CHES_CLIENT_PASSWORD }} \
-            -p EMAIL_TOKEN_URL='https://oidc.gov.bc.ca/auth/realms/jbd6rnxw/protocol/openid-connect/token' \
-            -p EMAIL_API_URL='https://ches.apps.silver.devops.gov.bc.ca/api/v1' \
-            -p NODE_ENV='production' | oc apply -f -
-          oc process -f .github/openshift/deploy.frontend.yml -p ZONE=${{ env.ZONE }} \
-            -p PROMOTE=${{ github.repository }}:${{ env.PREV }}-frontend | oc apply -f -
+  # deploy-prod:
+  #   name: PROD Deployment
+  #   needs:
+  #     - zap-backend
+  #     - zap-frontend
+  #   runs-on: ubuntu-latest
+  #   environment:
+  #     name: prod
+  #   env:
+  #     ZONE: prod
+  #     PREV: test
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Deploy
+  #       run: |
+  #         # Login to OpenShift and select project
+  #         oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
+  #         oc project ${{ secrets.OC_NAMESPACE }}
 
-          # Follow any active rollouts (see deploymentconfigs)
-          oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-database -w
-          oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-backend -w
-          oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-frontend -w
+  #         # Clear stale images for import/replacement
+  #         if [ $(oc get is -l app=${{ env.NAME }}-${{ env.ZONE }} -o name | grep -v database | wc -l) -gt 0 ]; then
+  #           oc delete is -l app=${{ env.NAME }}-${{ env.ZONE }}
+  #         fi
 
-          # Remove completed build runs, build pods and deployment pods
-          for p in $(oc get po | grep "Completed" | awk '{print $1}')
-          do
-            oc delete po ${p}
-          done
+  #         # Cancel db backup rollout if exists
+  #         if [ $(oc get dc -l app=backup-container -o name | wc -l) -gt 0 ]; then
+  #           oc rollout cancel dc/${{ env.NAME }}-${{ env.ZONE }}-dbbackup 2> /dev/null \
+  #             || true && echo "No rollout in progress"
+  #         fi
 
-          # Restart db backup rollout if exists
-          if [ $(oc get dc -l app=backup-container -o name | wc -l) -gt 0 ]; then
-            oc rollout latest dc/${{ env.NAME }}-${{ env.ZONE }}-dbbackup 2> /dev/null \
-              || true && echo "Rollout in progress"
-            oc logs -f dc/${{ env.NAME }}-${{ env.ZONE }}-dbbackup
-          fi
+  #         # Create frontend config (Remove the old one if exists)
+  #         oc delete configmap ${{ env.NAME }}-${{ env.ZONE }}-frontend 2> /dev/null \
+  #           || true && echo "No existing frontend config"
+  #         oc create configmap ${{ env.NAME }}-${{ env.ZONE }}-frontend  \
+  #           --from-literal=config.js="const config = (() => { return { VITE_BACKEND_URL: 'https://${{ env.NAME }}-${{ env.ZONE }}-backend.apps.silver.devops.gov.bc.ca'}; })();"
+
+  #         # Process and apply deployment templates
+  #         oc process -f .github/openshift/deploy.database.yml -p ZONE=${{ env.ZONE }} | oc apply -f -
+  #         oc process -f .github/openshift/deploy.backend.yml -p ZONE=${{ env.ZONE }} \
+  #           -p PROMOTE=${{ github.repository }}:${{ env.PREV }}-backend \
+  #           -p EMAIL_USERNAME=${{ secrets.CHES_SERVICE_CLIENT }} \
+  #           -p EMAIL_PASSWORD=${{ secrets.CHES_CLIENT_PASSWORD }} \
+  #           -p EMAIL_TOKEN_URL='https://oidc.gov.bc.ca/auth/realms/jbd6rnxw/protocol/openid-connect/token' \
+  #           -p EMAIL_API_URL='https://ches.apps.silver.devops.gov.bc.ca/api/v1' \
+  #           -p NODE_ENV='production' | oc apply -f -
+  #         oc process -f .github/openshift/deploy.frontend.yml -p ZONE=${{ env.ZONE }} \
+  #           -p PROMOTE=${{ github.repository }}:${{ env.PREV }}-frontend | oc apply -f -
+
+  #         # Follow any active rollouts (see deploymentconfigs)
+  #         oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-database -w
+  #         oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-backend -w
+  #         oc rollout status dc/${{ env.NAME }}-${{ env.ZONE }}-frontend -w
+
+  #         # Remove completed build runs, build pods and deployment pods
+  #         for p in $(oc get po | grep "Completed" | awk '{print $1}')
+  #         do
+  #           oc delete po ${p}
+  #         done
+
+  #         # Restart db backup rollout if exists
+  #         if [ $(oc get dc -l app=backup-container -o name | wc -l) -gt 0 ]; then
+  #           oc rollout latest dc/${{ env.NAME }}-${{ env.ZONE }}-dbbackup 2> /dev/null \
+  #             || true && echo "Rollout in progress"
+  #           oc logs -f dc/${{ env.NAME }}-${{ env.ZONE }}-dbbackup
+  #         fi
